# Generated by Django 3.2 on 2022-02-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dccustomer',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
