# Generated by Django 3.2 on 2022-02-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_dccustomer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dccustomer',
            name='dob',
            field=models.CharField(max_length=200, null=True, verbose_name='Date of birth'),
        ),
    ]
