# Generated by Django 3.2 on 2022-02-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_dccustomer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(db_index=True, max_length=200, verbose_name='Policy Type')),
                ('premium', models.DecimalField(decimal_places=3, default=200, max_digits=200, verbose_name='Premium')),
                ('cover', models.DecimalField(decimal_places=3, default=200000, max_digits=200, verbose_name='Cover')),
                ('state', models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Quoted'), (2, 'Active')], default=0, null=True, verbose_name='State')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_policies', to='customer.dccustomer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DcPolicyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Quoted'), (2, 'Active')], default=0, null=True, verbose_name='State')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='policy.dcpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
